// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230926110459_new2")]
    partial class new2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OdeljenjeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specijalizacija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OdeljenjeId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Domain.Karton", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Dijagnoza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LekarId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("OdeljenjeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PacijentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Terapija")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LekarId");

                    b.HasIndex("OdeljenjeId");

                    b.HasIndex("PacijentId");

                    b.ToTable("Kartoni");
                });

            modelBuilder.Entity("Domain.Napomena", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("KartonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NezeljenoDejstvo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primedba")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SestraId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("KartonId");

                    b.HasIndex("SestraId");

                    b.ToTable("Napomene");
                });

            modelBuilder.Entity("Domain.Odeljenje", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojKreveta")
                        .HasColumnType("int");

                    b.Property<int>("BrojPacijenata")
                        .HasColumnType("int");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecijalizacijaNaziv")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Odeljenja");
                });

            modelBuilder.Entity("Domain.Pacijent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BrojGodina")
                        .HasColumnType("int");

                    b.Property<string>("Ime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JMBG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LekarId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("OdeljenjeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Pol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LekarId");

                    b.HasIndex("OdeljenjeId");

                    b.ToTable("Pacijenti");
                });

            modelBuilder.Entity("Domain.Pregled", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Anamneza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Dijagnoza")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("KartonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LekarId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Terapija")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("VremePregleda")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("KartonId");

                    b.HasIndex("LekarId");

                    b.ToTable("Pregledi");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RoleId", "UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("Domain.AppUser", b =>
                {
                    b.HasOne("Domain.Odeljenje", "Odeljenje")
                        .WithMany("Osoblje")
                        .HasForeignKey("OdeljenjeId");

                    b.Navigation("Odeljenje");
                });

            modelBuilder.Entity("Domain.Karton", b =>
                {
                    b.HasOne("Domain.AppUser", "Lekar")
                        .WithMany("Kartoni")
                        .HasForeignKey("LekarId");

                    b.HasOne("Domain.Odeljenje", "Odeljenje")
                        .WithMany()
                        .HasForeignKey("OdeljenjeId");

                    b.HasOne("Domain.Pacijent", "Pacijent")
                        .WithMany("Kartoni")
                        .HasForeignKey("PacijentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Lekar");

                    b.Navigation("Odeljenje");

                    b.Navigation("Pacijent");
                });

            modelBuilder.Entity("Domain.Napomena", b =>
                {
                    b.HasOne("Domain.Karton", "Karton")
                        .WithMany("Nampomene")
                        .HasForeignKey("KartonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.AppUser", "Sestra")
                        .WithMany()
                        .HasForeignKey("SestraId");

                    b.Navigation("Karton");

                    b.Navigation("Sestra");
                });

            modelBuilder.Entity("Domain.Pacijent", b =>
                {
                    b.HasOne("Domain.AppUser", "Lekar")
                        .WithMany()
                        .HasForeignKey("LekarId");

                    b.HasOne("Domain.Odeljenje", "Odeljenje")
                        .WithMany("Pacijenti")
                        .HasForeignKey("OdeljenjeId");

                    b.Navigation("Lekar");

                    b.Navigation("Odeljenje");
                });

            modelBuilder.Entity("Domain.Pregled", b =>
                {
                    b.HasOne("Domain.Karton", "Karton")
                        .WithMany("Pregledi")
                        .HasForeignKey("KartonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Domain.AppUser", "Lekar")
                        .WithMany("Pregledi")
                        .HasForeignKey("LekarId");

                    b.Navigation("Karton");

                    b.Navigation("Lekar");
                });

            modelBuilder.Entity("Domain.AppUser", b =>
                {
                    b.Navigation("Kartoni");

                    b.Navigation("Pregledi");
                });

            modelBuilder.Entity("Domain.Karton", b =>
                {
                    b.Navigation("Nampomene");

                    b.Navigation("Pregledi");
                });

            modelBuilder.Entity("Domain.Odeljenje", b =>
                {
                    b.Navigation("Osoblje");

                    b.Navigation("Pacijenti");
                });

            modelBuilder.Entity("Domain.Pacijent", b =>
                {
                    b.Navigation("Kartoni");
                });
#pragma warning restore 612, 618
        }
    }
}
